### ISSUE TITLE
Girder permission failure on non-public collection (Heliconia, as an example)

### ISSUE THREAD

**Issue by curtislisle** [Kitware/flow#150]
Heliconia is a private collection set with ArborGroup write and individuals granted owner permission.  We can upload and view items in the collection through the Arbor interface, but Romanesco steps fail because girder's item/download seems to have user=None. 

HTTP fetch failed (https://arbor.kitware.com/girder/api/v1/item/558d875ed591e49e60b4f078/download). Response: {"message": **"Read access denied for folder 54d2ae24d591e41a99bd214c (user None)."**, "type": "access"}<class 'requests.exceptions.HTTPError'>: 401 Client Error: Unauthorized  File "/data/celery/source/romanesco/romanesco/__main__.py", line 24, in run

**Comment by curtislisle** [comment]
When I execute a download directly using the girder API, access to the item works, so I think Arbor isn't passing the user credentials correctly through to girder. 

For example, the following works for me at the girder interface, but not when trying to access the item through Arbor:

https://arbor.kitware.com:443/girder/api/v1/./item/558d875ed591e49e60b4f078/download

**Comment by curtislisle** [comment]
This may be related to #46 but it seems more severe.  Currently all users receive a permission denied message when trying to run analyses on items in the non-public collection, even when the logged in user has "is owner" permission.  Doesn't seem like user credentials make it into girder for checking.

**Comment by curtislisle** [comment]
This problem still persists as of 11/3.  Can someone provide insight as to where to explore that the user invoking a job doesn't seem to be passed to romanesco?  Therefore when romanesco tries to read items, girder denies the anonymous read.  I just tried creating a private collection with the current origin/master and tried to run an analysis while logged in as Admin/girder.   I received the denial response below.  To me, I am suspicious of "(user None)".

HTTP fetch failed (http://localhost:9080/girder/api/v1/item/5638f0a956c02c05b054f990/download). Response: {"message": "Read access denied for folder 5638efc356c02c05b054f981 (user None).", "type": "access"}<class 'requests.exceptions.HTTPError'>: 401 Client Error: Unauthorized  File "/vagrant/romanesco/romanesco/__main__.py", line 26, in run    retval = romanesco.run(*pargs, **kwargs)  File "/vagrant/romanesco/romanesco/utils.py", line 285, in wrapped    return fn(*args, **kwargs)  File "/vagrant/romanesco/romanesco/__init__.py", line 234, in run    if validate and not romanesco.isvalid(task_input["type"], d, **kwargs):  File "/vagrant/romanesco/romanesco/__init__.py", line 104, in isvalid    binding["data"] = romanesco.io.fetch(binding, **kwargs)  File "/vagrant/romanesco/romanesco/io/__init__.py", line 83, in fetch    return _fetch_map[mode](spec, **kwargs)  File "/vagrant/romanesco/romanesco/io/http.py", line 35, in fetch    request.raise_for_status()  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 834, in raise_for_status    raise HTTPError(http_error_msg, response=self)

**Comment by zachmullen** [comment]
Hm, romanesco is failing to properly authenticate when making the request for the data, meaning it's not passing the token field correctly.

**Comment by jeffbaumes** [comment]
I am able to have an admin user send a table to a Romanesco script in a private collection without an issue, but I do not have a Vagrant-based install. @zachmullen are you able to replicate - I believe you have a recent Vagrant install?

**Comment by zachmullen** [comment]
I'll spin up vagrant and try it out.

**Comment by curtislisle** [comment]
Unless I’m mistaken, this is what I just tried in a vagrant install.  i put a table in a private collection and tried to run a script on it through the Flow interface while logged in as the default ‘girder’ admin account.   That is how I generated the error.  I am using reversion:

commit 343371bdd32c54cbbf1ac5850358fe4e16f5a773
Merge: eb221f5 b25ffea
Author: Zach Mullen <zach.mullen@kitware.com>
Date:   Mon Nov 2 16:13:07 2015 -0500

**Comment by zachmullen** [comment]
@curtislisle I just spun up a fresh vagrant install on the same commit and then changed the **Default** collection and everything underneath it to be private, but I was still able to run the task successfully as the **girder** user. The task downloaded and printed out some data from a file I uploaded to the collection.

However, when I refreshed the page and tried it again, it did fail with the error you are seeing -- so it looks like this only happens for data that was uploaded in a previous session. I'll dig into the code and see if I can figure out why that's happening.

**Comment by zachmullen** [comment]
So, looking at the outputs from the two jobs, it's clear what's going wrong:

![screen shot 2015-11-03 at 2 53 47 pm](https://cloud.githubusercontent.com/assets/555959/10919798/be374986-823a-11e5-9953-b512fc0dea44.png)

The successful one has the following input specifier. Notice that the URL is bad, but the download isn't necessary at all since the data is simply inlined in the `data` field (seems like a bad idea, but it does cause it to work...)

![screen shot 2015-11-03 at 2 54 49 pm](https://cloud.githubusercontent.com/assets/555959/10919820/df224038-823a-11e5-9fc2-dac42dc3ebca.png)

For the failed one, the data is not inlined, and the `url` is actually the right one, but no auth header is set, hence the 401.

![screen shot 2015-11-03 at 2 56 17 pm](https://cloud.githubusercontent.com/assets/555959/10919855/0f53a706-823b-11e5-8fe6-0cefe5c80fbc.png)

My question for @jeffbaumes would be, is this difference by design? Is the data supposed to be inlined but only if it's in the same session where it was uploaded? In any case, I'll fix up the bug, and remove the extraneous stuff from the input spec, was just curious why the data was only being inlined some of the time.

**Comment by curtislisle** [comment]
Good catch identifying the temporal semantics of how the failure is occurring. Thanks for looking at this.

**Comment by curtislisle** [comment]
Is the inlining to support the use case of browser local storage data?  I like being able to run analyses on data we aren't certain is important enough to  store in a girder collection yet.  This is a design idea we've had in Arbor.  Maybe l'm confusing things, though.

**Comment by zachmullen** [comment]
I'm guessing that must be the reason

**Comment by jeffbaumes** [comment]
@zachmullen what it should be is that if the data is inlined, it should use it. This supports the use case of being not logged in where the user just dropped in some data. But all this about extraneous parameters and bad URLs are definitely are not by design - please go ahead and clean that up :)

One question is whether we should delete inlined data once it's stored in Girder. I think the answer is yes.
