### ISSUE TITLE
cannot save table:rows type on Arbor AWS

### ISSUE THREAD

**Issue by curtislisle** [Kitware/flow#179]
I was testing the Open Tree methods in Arbor and created a new output table of table.rows type.  When I saved to a collection, the type was set as "rows" during the save operation in the UI, but the table is saved as type .undefined.undefined instead, so the "format" error comes up when trying to process or download the table.  

It may be as simple as the UI not saving the correct types for the rows argument, but "rows" is the default and it doesn't work.   Quick fix could be to change the default table format to CSV.

**Comment by jeffbaumes** [comment]
Ok I think @danlamanna and I got to the bottom of this. The issue is not with the `rows` format, it's the fact that `rows` should not be in the download/save list at all, since it is an in-memory (not serializable) format. It's the `rows.json` format that you want. @danlamanna will push a fix (which should be a small amount of client JS code) to filter that list to show serializable formats only.

**Comment by jeffbaumes** [comment]
@curtislisle even before the fix you can make sure using `rows.json` does what you want it to do.
