### ISSUE TITLE
Arbor apps only work when user is logged in

### ISSUE THREAD

**Issue by lukejharmon** [Kitware/flow#214]
The Arbor apps only work when I am logged in to girder. For example:

arbor.arborworkflows.com/ancestral-state/

I can put in data files and pick a column if I am not logged in - but the analysis fails. When I am logged in it works.

**Comment by curtislisle** [comment]
The "Flow" execution fails with a missing userid key.  I found this to be the case when writing other web apps recently.  Is it our position that someone has to be logged in in order to execute Girder jobs?   I can see the security case for requiring this, but it runs counter to Arbor's goal of being accessible.  Any suggestions how to resolve?

{"message": "KeyError: KeyError('userId',)", "trace": [["girder/api/rest.py", 428, "endpointDecorator", "val = fun(self, args, kwargs)"], ["girder/api/rest.py", 968, "POST", "return self.handleRoute(method, path, params)"], ["girder/api/rest.py", 742, "handleRoute", "val = handler(**kwargs)"], ["girder/api/rest.py", 1017, "wrapped", "return fn(self.ctx, *args, **kwargs)"], ["girder/api/rest.py", 273, "wrapped", "return fun(*args, **kwargs)"], ["/opt/girder/plugins/flow/server/__init__.py", 263, "flowRun", "return runAnalysis(user, analysis, kwargs, item)"], ["/opt/girder/plugins/flow/server/__init__.py", 86, "runAnalysis", "jobModel.scheduleJob(job)"], ["/opt/girder/plugins/jobs/server/models/job.py", 220, "scheduleJob", "events.trigger('jobs.schedule', info=job)"], ["girder/events.py", 260, "trigger", "handler['handler'](e)"], ["/opt/girder/plugins/worker/server/__init__.py", 89, "schedule", "job, status=JobStatus.QUEUED)"], ["/opt/girder/plugins/jobs/server/models/job.py", 271,

**Comment by jeffbaumes** [comment]
Users and analysis folders should be able to be whitelisted through the Girder Flow plugin settings to allow not-signed-in user.

If you navigate to the folder in Girder where the analysis is saved, copy the hash that is in the URL, and paste it in the "Safe folders (JSON list of folder IDs)" inside a JSON list, like

```
["5919aad4fa7d8c60ede60659"]
```

Alternately, you should be able to totally open things up by unchecking "Require authorization to run tasks".

Let me know if these paths do not work.

**Comment by curtislisle** [comment]
Oh yes, thanks, Jeff.  I forgot about the whitelisted folders option.  I
vote for moving the methods we want to run without login into a
ArborAppsSupport collection or something similar, then whitelist this. I
feel it is too dangerous on a public site to allow anybody to run arbitrary
tasks.

**Comment by lukejharmon** [comment]
OK here is what I am seeing right now. I am using arbordev.arborworkflows.com. Either I am mixed up or things are not behaving as expected!

The apps don’t work unless one is logged in. BUT the box "Require authorization to run tasks” is not checked.
<img width="925" alt="screen shot 2017-05-24 at 11 17 11 am" src="https://cloud.githubusercontent.com/assets/1669734/26418989/17e70d5c-4073-11e7-9260-ba49617ece75.png">

I get:

<img width="1208" alt="screen shot 2017-05-24 at 11 21 35 am" src="https://cloud.githubusercontent.com/assets/1669734/26419021/30383534-4073-11e7-9310-1688fa962926.png">

If I try to whitelist:

<img width="1013" alt="screen shot 2017-05-24 at 11 32 08 am" src="https://cloud.githubusercontent.com/assets/1669734/26419494/cb5b4ca8-4074-11e7-8ec4-e892d08d4f15.png">

I still get an error if not logged in:

<img width="1210" alt="screen shot 2017-05-24 at 11 32 58 am" src="https://cloud.githubusercontent.com/assets/1669734/26419518/d3f039be-4074-11e7-8d5f-e5c83603ec35.png">

Thanks for looking into this!

**Comment by lukejharmon** [comment]
oh, and the app i am trying to run is:

http://52.204.9.236/PGLS-twovars/

which uses the function: "PGLS_2traits-app" in the collection: "functionsForArborApps"

**Comment by curtislisle** [comment]
I re-inserted the folder IDs into the Flow plugin.  It seems to me like the task is executing now, and we came across a run-time R error.  Is the lack of data properly going into the function a failure of Arbor somehow, or does this error make sense in the code, as if Arbor is working well and there is just a code bug in the analysis? 

"Error in recalc.corStruct(object[[i]], conLin) : \n  NA/NaN/Inf in foreign function call (arg 4)\n", "status": “FAILURE"

**Comment by curtislisle** [comment]
Still a bug in the girder login layer?  I just added a safe folder entry in the Flow plugin for the Default folder on the public arbor (http://52.204.46.78/phylogenetic-signal/ <http://52.204.46.78/phylogenetic-signal/>) to make the easy mode apps available to non-users, like we used to allow. However, when I try an easy mode app without being logged in, I receive a runtime KeyError in Girder.  It doesn’t seem to be a permission error, to be fixed by whitelisting, I believe it is a runtime error inside Girder that happens earlier than permission checking.   I believe I’ve reported this before, and we may have thought it was resolved, but it still plagues the public Arbor instance.  

It seems identical to what Luke was experiencing last month and we thought we fixed.  When I push “Go” on the phylosignal app, I receive (in the console):

VM1082:1 POST http://52.204.46.78/api/v1/item/577b6a8054cdbf3c14cc4612/flow 500 (Internal Server Error)

util.js:195 Error encountered: {"message": "KeyError: KeyError('userId',)", "trace": [["girder/api/rest.py", 428, "endpointDecorator", "val = fun(self, args, kwargs)"], ["girder/api/rest.py", 968, "POST", "return self.handleRoute(method, path, params)"], ["girder/api/rest.py", 742, "handleRoute", "val = handler(**kwargs)"], ["girder/api/rest.py", 1017, "wrapped", "return fn(self.ctx, *args, **kwargs)"], ["girder/api/rest.py", 273, "wrapped", "return fun(*args, **kwargs)"], ["/opt/girder/plugins/flow/server/__init__.py", 263, "flowRun", "return runAnalysis(user, analysis, kwargs, item)"], ["/opt/girder/plugins/flow/server/__init__.py", 86, "runAnalysis", "jobModel.scheduleJob(job)"], ["/opt/girder/plugins/jobs/server/models/job.py", 220, "scheduleJob", "events.trigger('jobs.schedule', info=job)"], ["girder/events.py", 260, "trigger", "handler['handler'](e)"], ["/opt/girder/plugins/worker/server/__init__.py", 89, "schedule", "job, status=JobStatus.QUEUED)"], ["/opt/girder/plugins/jobs/server/models/job.py", 271, "updateJob", "if notify and job['userId']:"]], "type": "internal"}

Could I request help to examine this?  Thanks. 

Curt

**Comment by jeffbaumes** [comment]
I remember this from before too. Can you try this patch in `plugins/jobs/server/models/job.py` and restart Girder?

Where you see this (or something like it) in the `createJob` function:
```
        if user:
            job['userId'] = user['_id']
            self.setUserAccess(job, user=user, level=AccessType.ADMIN)
```

Add the following else case directly below it:
```
        else:
            job['userId'] = None
```

**Comment by curtislisle** [comment]
Yes, this works.  I just made this change on the public Arbor server.  (arbor.arborworkflows.com <http://arbor.arborworkflows.com/>).   I am able to run the easy mode apps (from the whitelist folder) without being logged in.  Thanks.

Curt

**Comment by jeffbaumes** [comment]
See https://github.com/girder/girder/pull/2157 for the fix proposed in Girder.
